import { useRef, useState, useEffect } from 'react';
import { motion, AnimatePresence, useScroll, useSpring, useTransform } from 'framer-motion';
import { 
  ArrowRight, 
  Play, 
  Facebook, 
  Twitter, 
  Instagram, 
  Globe,
  Search,
  ShoppingCart,
  Menu as MenuIcon,
  Cpu,
  Waves,
  Zap,
  Settings,
  ShieldCheck,
  Award,
  CheckCircle2,
  Users,
  MessageSquare,
  Star,
  Flame,
  BadgeCheck
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import NeuralynNavbar from '../../components/layout/customer/NeuralynNavbar';
import NeuralynFooter from '../../components/layout/customer/NeuralynFooter';
import homepageImg from '../../assets/images/homepage.png';

// Product images generated by AI
import machine1500w from '../../assets/images/machine1500w.png';
import machine400w from '../../assets/images/machine400w.png';
import machine3000w from '../../assets/images/machine3000w.png';
import liquid5l from '../../assets/images/liquid5l.png';

const FloatingOrb = ({ color, size, top, left, delay }) => (
  <motion.div
    animate={{
      y: [0, -30, 0],
      x: [0, 20, 0],
      scale: [1, 1.05, 1],
      opacity: [0.2, 0.4, 0.2],
    }}
    transition={{
      duration: 10 + Math.random() * 5,
      repeat: Infinity,
      delay,
      ease: "easeInOut"
    }}
    className="absolute pointer-events-none blur-[100px] rounded-full z-0 opacity-20"
    style={{
      backgroundColor: color,
      width: size,
      height: size,
      top,
      left,
    }}
  />
);

const PerspectiveGrid = () => (
  <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none opacity-[0.15] bg-white/10 rounded-[2rem] md:rounded-[3rem]">
    <div 
      className="absolute inset-0"
      style={{
        backgroundImage: `linear-gradient(#4981cf 1px, transparent 1px), linear-gradient(90deg, #4981cf 1px, transparent 1px)`,
        backgroundSize: '25px 25px',
        perspective: '1000px',
        transform: 'rotateX(60deg) scale(2) translateY(-40px)',
        transformOrigin: '50% 100%',
        maskImage: 'linear-gradient(to top, black 50%, transparent 100%)'
      }}
    />
  </div>
);

export default function NeuralynHome() {
  const navigate = useNavigate();

  return (
    <div className="bg-[#e8ebf2] font-sans selection:bg-[#4981cf] selection:text-white overflow-x-hidden scroll-smooth custom-scrollbar relative">
      <NeuralynNavbar />

      {/* Hero Section */}
      <section 
        className="relative min-h-[90vh] flex items-center pt-24 pb-20 bg-[#4981cf] z-30 shadow-xl" 
        id="home"
      >
        <FloatingOrb color="#ffffff" size="250px" top="-5%" left="60%" delay={0} />
        <FloatingOrb color="#cadaee" size="200px" top="40%" left="-10%" delay={2} />
        
        <div className="container mx-auto px-6 md:px-16 relative z-10 grid lg:grid-cols-2 gap-10 items-center">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1 }}
            className="text-center lg:text-left"
          >
            <h2 className="text-[#cadaee] font-heading font-black tracking-[0.4em] uppercase text-[9px] mb-6 block drop-shadow-sm">Thiết Bị Sân Khấu Chuyên Nghiệp DuongDIY</h2>
            <h1 className="text-4xl md:text-[4rem] font-heading font-black text-white leading-[1.1] tracking-tight mb-8 drop-shadow-lg">
              Kỹ Thuật Tạo Khói <br className="hidden md:block"/> <span className="text-[#cadaee]">Đỉnh Cao Pro</span>
            </h1>
            <p className="text-white text-base md:text-lg mb-10 max-w-md mx-auto lg:mx-0 leading-relaxed font-semibold drop-shadow-sm opacity-85">
              DuongDIY cung cấp máy tạo khói, dung dịch khói chuẩn sân khấu quốc tế. 
              Hiệu năng mạnh mẽ, bền bỉ và an toàn tuyệt đối.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-5">
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#ffffff', color: '#4981cf' }}
                onClick={() => navigate('/catalog')}
                className="w-full sm:w-auto bg-white text-[#4981cf] px-12 py-5 rounded-full font-black text-[10px] tracking-[0.2em] uppercase transition-all shadow-2xl"
              >
                XEM BỘ SƯU TẬP
              </motion.button>
              <button className="flex items-center gap-4 text-white font-black tracking-[0.2em] text-[10px] uppercase hover:text-[#cadaee] transition-colors group">
                <div className="w-12 h-12 rounded-full border-2 border-white/30 flex items-center justify-center group-hover:bg-white/10 group-hover:border-white transition-all">
                  <Play className="w-4 h-4 fill-current" />
                </div>
                VIDEO THỰC TẾ
              </button>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1.2, type: "spring" }}
            className="hidden lg:block relative text-right"
          >
            <div className="absolute -inset-10 bg-white/10 blur-[80px] rounded-full animate-pulse" />
            <img 
              src={homepageImg} 
              alt="Professional Fog Machine" 
              className="relative z-10 w-full max-w-[550px] h-auto ml-auto drop-shadow-[0_25px_25px_rgba(0,0,0,0.4)] hover:scale-105 transition-transform duration-700"
            />
          </motion.div>
        </div>
      </section>

      {/* Production Process */}
      <section className="relative py-24 bg-[#e8ebf2] z-20" id="about">
        <div className="container mx-auto px-6 md:px-16 grid lg:grid-cols-2 gap-20 items-center relative z-10">
          <motion.div 
            whileInView={{ opacity: 1, y: 0 }}
            initial={{ opacity: 0, y: 30 }}
            viewport={{ once: true }}
            className="relative group rounded-[3rem] overflow-hidden shadow-2xl w-full aspect-video bg-[#4981cf] flex items-center justify-center border-4 border-white"
          >
            <PerspectiveGrid />
            <div className="absolute inset-0 bg-[#4981cf]/10 flex items-center justify-center z-10">
              <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center text-[#4981cf] cursor-pointer hover:scale-110 transition-transform shadow-2xl border-4 border-white/20">
                <Play className="w-7 h-7 fill-current ml-1" />
              </div>
            </div>
          </motion.div>

          <div className="space-y-8 text-center lg:text-left">
            <span className="text-[#4981cf] font-heading font-black tracking-[0.3em] uppercase text-[10px]">CHẤT LƯỢNG LÀM NÊN THƯƠNG HIỆU</span>
            <h2 className="text-4xl md:text-5xl font-heading font-black text-[#1a365d] leading-tight tracking-tight">
              Tiêu Chuẩn <br className="hidden md:block"/><span className="text-[#4981cf]">Chế Tác Pro</span>
            </h2>
            <p className="text-[#1a365d] text-base md:text-lg leading-relaxed font-bold opacity-75 max-w-lg mx-auto lg:mx-0">
              Mọi thiết bị xuất xưởng từ DuongDIY đều phải vượt qua 24 giờ test liên tục, đảm bảo độ ổn định tuyệt đối.
            </p>
            <div className="grid grid-cols-2 gap-6 pt-4">
              <div className="space-y-2 p-5 bg-white rounded-2xl shadow-sm border border-[#cadaee]">
                <div className="text-3xl font-black text-[#4981cf]">100%</div>
                <div className="text-[9px] font-black uppercase tracking-widest text-[#1a365d]">LINH KIỆN CAO CẤP</div>
              </div>
              <div className="space-y-2 p-5 bg-white rounded-2xl shadow-sm border border-[#cadaee]">
                <div className="text-3xl font-black text-[#4981cf]">5.0k+</div>
                <div className="text-[9px] font-black uppercase tracking-widest text-[#1a365d]">DỰ ÁN TIN DÙNG</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Technical Excellence */}
      <section className="py-24 bg-white relative z-10">
        <div className="container mx-auto px-6 md:px-16">
          <div className="text-center mb-16 space-y-3">
             <span className="text-[#89aad3] font-heading font-black tracking-[0.3em] uppercase text-[10px]">CÔNG NGHỆ ĐI ĐẦU</span>
             <h2 className="text-3xl md:text-4xl font-heading font-black text-[#1a365d] tracking-tight">Đặc Tính Kỹ Thuật</h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { icon: Cpu, title: "Smart Chip Core", desc: "Điều khiển nhiệt độ chính xác tới 0.1 độ C." },
              { icon: Waves, title: "Lưu Lượng Dày Mịn", desc: "Hệ thống vòi phun hợp kim cao cấp." },
              { icon: Settings, title: "DMX 512 Pro", desc: "Tương thích hoàn hảo với mọi bàn điều khiển." },
              { icon: ShieldCheck, title: "An Toàn Tuyệt Đối", desc: "Cảm biến tự ngắt thông minh." }
            ].map((item, idx) => (
              <div key={idx} className="group p-8 rounded-[2rem] bg-[#e8ebf2]/40 border-2 border-transparent hover:border-[#4981cf] hover:bg-white transition-all duration-500 shadow-sm hover:shadow-xl">
                <div className="w-12 h-12 bg-[#4981cf] text-white rounded-xl flex items-center justify-center mb-6 shadow-lg shadow-[#4981cf]/30 group-hover:rotate-12 transition-transform">
                  <item.icon className="w-6 h-6" />
                </div>
                <h4 className="text-lg md:text-xl font-heading font-black text-[#1a365d] mb-4">{item.title}</h4>
                <p className="text-[#1a365d] text-sm font-bold opacity-70 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Product List - 2 Columns on Mobile, Shrunken Elements */}
      <section className="relative py-20 md:py-24 bg-[#4981cf] z-10 shadow-inner" id="products">
        <div className="container mx-auto px-4 md:px-16">
          <div className="text-center max-w-2xl mx-auto mb-12 md:mb-16">
            <h2 className="text-3xl md:text-5xl font-heading font-black text-white mb-4 md:mb-6 tracking-tight drop-shadow-md">Sản Phẩm Tiêu Biểu</h2>
            <p className="text-[#cadaee] font-black tracking-[0.15em] md:tracking-[0.2em] text-[8px] md:text-[10px] uppercase italic opacity-85">Thiết bị tối tân - Hiệu ứng đỉnh cao</p>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 md:gap-10">
            {[
              { name: "Máy Khói 1500W DMX", price: "2.450.000đ", img: machine1500w, badge: "Best Seller", desc: "Điều khiển Pro, chuyên nghiệp." },
              { name: "Máy Khói 400W Mini", price: "850.000đ", img: machine400w, badge: "New", desc: "Nhỏ gọn, phòng karaoke gia đình." },
              { name: "Máy Khói Lạnh 3000W", price: "5.800.000đ", img: machine3000w, badge: "Premium", desc: "Khói bay là là mặt đất." },
              { name: "Dung Dịch Khói 5L", price: "250.000đ", img: liquid5l, badge: "Essential", desc: "Khói trắng, dày lâu tan." },
              { name: "Máy Khói 900W Pro", price: "1.250.000đ", img: machine1500w, badge: "Hot", desc: "Mạnh mẽ cho quán Bar, Club." },
              { name: "Combo Stage Pro", price: "7.500.000đ", img: machine3000w, badge: "Save 15%", desc: "Giải pháp toàn diện sân khấu." },
            ].map((item, idx) => (
              <motion.div 
                key={idx}
                whileHover={{ y: -5 }}
                className="group bg-white rounded-[1.5rem] md:rounded-[2.5rem] overflow-hidden shadow-xl transition-all duration-500 flex flex-col h-full"
              >
                <div className="relative h-36 sm:h-56 md:h-64 overflow-hidden bg-[#e8ebf2]">
                  <div className="absolute top-2 left-2 md:top-4 md:left-4 z-20">
                     <span className="bg-[#4981cf] text-white px-2 md:px-4 py-1 md:py-1.5 rounded-full font-black text-[6px] md:text-[8px] uppercase tracking-widest shadow-lg">
                       {item.badge}
                     </span>
                  </div>
                  <motion.img 
                    whileHover={{ scale: 1.1 }}
                    transition={{ duration: 0.8 }}
                    src={item.img} 
                    className="w-full h-full object-contain p-4 md:p-8"
                    alt={item.name}
                  />
                </div>

                <div className="p-4 md:p-8 flex flex-col flex-1">
                  <h3 className="text-xs md:text-xl font-heading font-black text-[#1a365d] mb-2 md:mb-4 leading-tight line-clamp-2 h-8 md:h-auto">{item.name}</h3>
                  <div className="flex items-center gap-0.5 md:gap-1.5 mb-3 md:mb-5 text-[#4981cf]">
                     {[...Array(5)].map((_, i) => <Star key={i} className="w-2 h-2 md:w-3.5 md:h-3.5 fill-current" />)}
                  </div>
                  <p className="hidden md:block text-[#1a365d] text-sm font-bold opacity-65 leading-relaxed mb-8 flex-1">{item.desc}</p>
                  
                  <div className="flex items-center justify-between mt-auto pt-3 md:pt-5 border-t border-[#e8ebf2]">
                    <span className="text-xs md:text-2xl font-black text-[#4981cf] tracking-tighter">{item.price}</span>
                    <button className="w-8 h-8 md:w-12 md:h-12 bg-[#1a365d] text-white rounded-lg md:rounded-xl flex items-center justify-center hover:bg-[#4981cf] transition-all shadow-xl active:scale-90">
                      <ShoppingCart className="w-4 h-4 md:w-5 md:h-5" />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
          
          <div className="mt-12 text-center">
             <button onClick={() => navigate('/catalog')} className="inline-flex items-center justify-center gap-2 bg-white/10 backdrop-blur-md border border-white/30 text-white px-8 py-4 md:px-12 md:py-5 rounded-full font-black text-[8px] md:text-[10px] tracking-[0.2em] uppercase hover:bg-white hover:text-[#4981cf] transition-all">
               TẤT CẢ SẢN PHẨM <ArrowRight className="w-3 h-3 md:w-4 md:h-4" />
             </button>
          </div>
        </div>
      </section>

      {/* Applications */}
      <section className="py-24 bg-[#e8ebf2] relative z-20">
        <div className="container mx-auto px-6 md:px-16">
          <div className="text-center mb-16 space-y-4">
              <span className="text-[#89aad3] font-heading font-black tracking-[0.3em] uppercase text-[10px]">KHÔNG GIAN BIẾN HÓA</span>
              <h2 className="text-4xl md:text-5xl font-heading font-black text-[#1a365d] tracking-tight">Ứng Dụng Thực Tế</h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { title: "Sân Khấu Pro", img: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80" },
              { title: "Club & Bar", img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80" },
              { title: "Studio Chụp Ảnh", img: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80" },
              { title: "Đám Cưới Cao Cấp", img: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80" }
            ].map((item, idx) => (
              <div key={idx} className="relative group h-[350px] md:h-[420px] rounded-[2.5rem] overflow-hidden shadow-xl border-4 border-white">
                <img src={item.img} className="absolute inset-0 w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" alt={item.title} />
                <div className="absolute inset-0 bg-gradient-to-t from-[#1a365d] to-transparent opacity-50 group-hover:opacity-80 transition-opacity" />
                <div className="absolute bottom-8 left-8 right-8 z-10">
                  <h4 className="text-2xl font-heading font-black text-white tracking-tight mb-3">{item.title}</h4>
                  <div className="w-10 h-1.5 bg-[#cadaee] rounded-full transform origin-left transition-transform scale-x-0 group-hover:scale-x-100" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="relative py-24 bg-[#89aad3] z-10 shadow-xl" id="testimonials">
        <div className="container mx-auto px-6 md:px-16 relative z-10">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="text-4xl md:text-5xl font-heading font-black text-white mb-6 tracking-tight drop-shadow-md">Khách Hàng Nói Gì</h2>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {[
              { name: "Anh Tuấn (DJ)", role: "QUÁN BAR QUẬN 1", text: "Máy khói DuongDIY đánh rất bốc, lượng khói phủ kín sàn chỉ trong vài giây. Tuyệt vời!" },
              { name: "Chị Lan Anh", role: "QUẢN LÝ SỰ KIỆN", text: "Máy chạy êm, ít bị nghẹt sưởi như mấy dòng giá rẻ trước đây. Sẽ ủng hộ dài lâu." },
              { name: "Minh Hoàng", role: "KARAOKE VIP", text: "Dung dịch khói bạc hà mùi cực kỳ dễ chịu. Máy khói mini 400W nhỏ mà có võ." }
            ].map((item, idx) => (
              <motion.div 
                key={idx}
                whileHover={{ y: -8, scale: 1.01 }}
                className="bg-white p-10 rounded-[2.5rem] shadow-2xl relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 w-16 h-16 bg-[#4981cf]/10 rounded-bl-[3rem]" />
                <p className="text-[#1a365d] text-lg font-bold leading-relaxed mb-8 italic">"{item.text}"</p>
                <div className="pt-6 border-t border-[#cadaee]">
                  <h4 className="text-xl font-black text-[#1a365d]">{item.name}</h4>
                  <p className="text-[#4981cf] text-[9px] font-black uppercase tracking-[0.2em] mt-2">{item.role}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-24 bg-white relative z-5">
        <div className="container mx-auto px-6 md:px-16">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl md:text-5xl font-heading font-black text-[#1a365d] tracking-tight">Câu Hỏi Thường Gặp</h2>
            </div>
            <div className="space-y-6">
              { [
                { q: "Làm thế nào để vệ sinh lõi sưởi máy khói?", a: "Sử dụng hỗn hợp nước cất và giấm trắng chạy máy trong 5-10 phút để loại bỏ cặn." },
                { q: "Có cần sử dụng dung dịch chuyên dụng không?", a: "Rất nên. Dung dịch DuongDIY tối ưu cho lõi sưởi, giúp kéo dài tuổi thọ thiết bị." },
                { q: "Chính sách bảo hành như thế nào?", a: "Bảo hành 12 tháng và hỗ trợ bảo trì trọn đời cho mọi khách hàng." }
              ].map((item, idx) => (
                <div key={idx} className="p-8 rounded-[2rem] bg-[#e8ebf2]/40 border-2 border-transparent hover:border-[#4981cf] transition-all group shadow-sm hover:shadow-lg">
                  <h4 className="text-lg md:text-xl font-heading font-black text-[#1a365d] mb-4 flex items-start gap-4">
                    <CheckCircle2 className="w-6 h-6 text-[#4981cf] shrink-0" />
                    <span>{item.q}</span>
                  </h4>
                  <p className="text-[#1a365d] text-base font-bold opacity-70 pl-10 leading-relaxed">{item.a}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Newsletter */}
      <section className="py-24 px-8 md:px-16 bg-[#e8ebf2] relative z-10">
        <div className="container mx-auto">
          <div className="bg-[#1a365d] rounded-[3.5rem] p-12 md:p-16 relative overflow-hidden flex flex-col lg:flex-row items-center justify-between gap-12 shadow-2xl">
             <div className="absolute top-0 right-0 w-1/2 h-full bg-[#4981cf]/15 blur-[100px] rounded-full" />
             <div className="space-y-6 relative z-10 text-center lg:text-left">
                <h2 className="text-4xl md:text-5xl font-heading font-black text-white tracking-tight leading-tight">Nhận Ưu Đãi <span className="text-[#cadaee]">15%</span></h2>
                <p className="text-white/80 text-lg font-bold italic">Báo giá sỉ và cập nhật công nghệ mới nhất từ DuongDIY.</p>
             </div>
             <div className="relative z-10 w-full max-w-md">
                <div className="flex bg-white p-2 rounded-3xl shadow-2xl">
                   <input type="email" placeholder="Email của bạn..." className="flex-1 bg-transparent px-6 py-4 text-[#1a365d] placeholder-[#1a365d]/30 outline-none font-black text-base" />
                   <button className="bg-[#4981cf] text-white px-8 py-4 rounded-2xl font-black text-[10px] uppercase tracking-[0.2em] hover:bg-[#1a365d] transition-all">GỬI</button>
                </div>
             </div>
          </div>
        </div>
      </section>

      <NeuralynFooter />
    </div>
  );
}
