import { motion } from 'framer-motion';
import { 
  ArrowRight, 
  Play, 
  Facebook, 
  Twitter, 
  Instagram, 
  Globe,
  Search,
  ShoppingCart,
  Menu as MenuIcon,
  Cpu,
  Waves,
  Zap,
  Settings,
  ShieldCheck,
  Award,
  CheckCircle2,
  Users,
  MessageSquare,
  Star,
  Flame,
  BadgeCheck
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import NeuralynNavbar from '../../components/layout/customer/NeuralynNavbar';
import homepageImg from '../../assets/images/homepage.png';

// Product images generated by AI
import machine1500w from '../../assets/images/machine1500w.png';
import machine400w from '../../assets/images/machine400w.png';
import machine3000w from '../../assets/images/machine3000w.png';
import liquid5l from '../../assets/images/liquid5l.png';

const FloatingOrb = ({ color, size, top, left, delay }) => (
  <motion.div
    animate={{
      y: [0, -40, 0],
      x: [0, 30, 0],
      scale: [1, 1.1, 1],
      opacity: [0.3, 0.6, 0.3],
    }}
    transition={{
      duration: 8 + Math.random() * 4,
      repeat: Infinity,
      delay,
      ease: "easeInOut"
    }}
    className="absolute pointer-events-none blur-[100px] rounded-full z-0 opacity-30"
    style={{
      backgroundColor: color,
      width: size,
      height: size,
      top,
      left,
    }}
  />
);

const PerspectiveGrid = () => (
  <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none opacity-[0.2] bg-white/10 rounded-[2rem] md:rounded-[3.5rem]">
    <div 
      className="absolute inset-0"
      style={{
        backgroundImage: `linear-gradient(#4981cf 1px, transparent 1px), linear-gradient(90deg, #4981cf 1px, transparent 1px)`,
        backgroundSize: '30px 30px',
        perspective: '1000px',
        transform: 'rotateX(60deg) scale(2.5) translateY(-50px)',
        transformOrigin: '50% 100%',
        maskImage: 'linear-gradient(to top, black 50%, transparent 100%)'
      }}
    />
  </div>
);

export default function NeuralynHome() {
  const navigate = useNavigate();

  return (
    <div className="bg-[#e8ebf2] font-sans selection:bg-[#4981cf] selection:text-white overflow-x-hidden scroll-smooth custom-scrollbar relative">
      <NeuralynNavbar />

      {/* Hero Section */}
      <section 
        className="relative min-h-screen flex items-center pt-24 md:pt-32 pb-20 md:pb-32 bg-[#4981cf] z-30 shadow-xl" 
        id="home"
      >
        <FloatingOrb color="#ffffff" size="300px" top="-5%" left="50%" delay={0} />
        <FloatingOrb color="#cadaee" size="250px" top="40%" left="-10%" delay={2} />
        
        <div className="container mx-auto px-6 md:px-12 relative z-10 grid lg:grid-cols-2 gap-12 items-center">
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1.2 }}
            className="text-center lg:text-left"
          >
            <h2 className="text-[#cadaee] font-heading font-black tracking-[0.3em] md:tracking-[0.5em] uppercase text-[9px] md:text-[10px] mb-6 md:mb-8 block drop-shadow-sm">Thiết Bị Sân Khấu Chuyên Nghiệp DuongDIY</h2>
            <h1 className="text-4xl sm:text-5xl md:text-[5.5rem] font-heading font-black text-white leading-[1.1] md:leading-[1.05] tracking-tighter mb-8 md:mb-10 drop-shadow-lg">
              Kỹ Thuật Tạo Khói <br className="hidden md:block"/> <span className="text-[#cadaee]">Đỉnh Cao Pro</span>
            </h1>
            <p className="text-white text-lg md:text-xl mb-10 md:mb-12 max-w-lg mx-auto lg:mx-0 leading-relaxed font-semibold drop-shadow-sm opacity-90">
              DuongDIY cung cấp máy tạo khói, dung dịch khói chuẩn sân khấu quốc tế. 
              Hiệu năng mạnh mẽ, bền bỉ và an toàn tuyệt đối cho mọi không gian sự kiện.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-5 md:gap-6">
              <motion.button
                whileHover={{ scale: 1.05, backgroundColor: '#ffffff', color: '#4981cf' }}
                onClick={() => navigate('/catalog')}
                className="w-full sm:w-auto bg-white text-[#4981cf] px-10 md:px-16 py-5 md:py-6 rounded-full font-black text-[10px] md:text-[11px] tracking-[0.2em] md:tracking-[0.3em] uppercase transition-all shadow-2xl"
              >
                XEM BỘ SƯU TẬP
              </motion.button>
              <button className="flex items-center gap-4 text-white font-black tracking-[0.2em] text-[10px] uppercase hover:text-[#cadaee] transition-colors group">
                <div className="w-12 h-12 md:w-14 md:h-14 rounded-full border-2 border-white/30 flex items-center justify-center group-hover:bg-white/10 group-hover:border-white transition-all">
                  <Play className="w-4 h-4 md:w-5 md:h-5 fill-current" />
                </div>
                VIDEO THỰC TẾ
              </button>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1.5, type: "spring" }}
            className="hidden lg:block relative"
          >
            <div className="absolute -inset-20 bg-white/10 blur-[120px] rounded-full animate-pulse" />
            <img 
              src={homepageImg} 
              alt="Professional Fog Machine" 
              className="relative z-10 w-full max-w-[650px] h-auto drop-shadow-[0_35px_35px_rgba(0,0,0,0.5)] hover:scale-105 transition-transform duration-700"
            />
          </motion.div>
        </div>
      </section>

      {/* Production Process */}
      <section 
        className="relative py-20 md:py-32 bg-[#e8ebf2] z-20" 
        id="about"
      >
        <div className="container mx-auto px-6 md:px-12 grid lg:grid-cols-2 gap-16 md:gap-32 items-center relative z-10">
          <motion.div 
            whileInView={{ opacity: 1, y: 0 }}
            initial={{ opacity: 0, y: 40 }}
            viewport={{ once: true }}
            className="relative group rounded-[2.5rem] md:rounded-[4rem] overflow-hidden shadow-2xl w-full aspect-video bg-[#4981cf] flex items-center justify-center border-4 border-white"
          >
            <PerspectiveGrid />
            <div className="absolute inset-0 bg-[#4981cf]/10 flex items-center justify-center z-10">
              <div className="w-16 h-16 md:w-24 md:h-24 bg-white rounded-full flex items-center justify-center text-[#4981cf] cursor-pointer hover:scale-110 transition-transform shadow-2xl border-4 border-white/20">
                <Play className="w-6 h-6 md:w-10 md:h-10 fill-current ml-1" />
              </div>
            </div>
          </motion.div>

          <div className="space-y-6 md:space-y-10 text-center lg:text-left">
            <span className="text-[#4981cf] font-heading font-black tracking-[0.3em] md:tracking-[0.4em] uppercase text-[10px] md:text-xs">CHẤT LƯỢNG LÀM NÊN THƯƠNG HIỆU</span>
            <h2 className="text-4xl md:text-7xl font-heading font-black text-[#1a365d] leading-[1.1] tracking-tighter">
              Tiêu Chuẩn <br className="hidden md:block"/><span className="text-[#4981cf]">Chế Tác Pro</span>
            </h2>
            <p className="text-[#1a365d] text-lg md:text-xl leading-relaxed font-bold opacity-80 max-w-xl mx-auto lg:mx-0">
              Mọi thiết bị xuất xưởng từ DuongDIY đều phải vượt qua 24 giờ test liên tục, đảm bảo độ ổn định tuyệt đối trong các điều kiện khắc nghiệt nhất.
            </p>
            <div className="grid grid-cols-2 gap-6 md:gap-10 pt-4 md:pt-6">
              <div className="space-y-2 md:space-y-3 p-5 md:p-6 bg-white rounded-2xl md:rounded-3xl shadow-sm border border-[#cadaee]">
                <div className="text-3xl md:text-4xl font-black text-[#4981cf]">100%</div>
                <div className="text-[9px] md:text-[11px] font-black uppercase tracking-widest text-[#1a365d]">LINH KIỆN CAO CẤP</div>
              </div>
              <div className="space-y-2 md:space-y-3 p-5 md:p-6 bg-white rounded-2xl md:rounded-3xl shadow-sm border border-[#cadaee]">
                <div className="text-3xl md:text-4xl font-black text-[#4981cf]">5.0k+</div>
                <div className="text-[9px] md:text-[11px] font-black uppercase tracking-widest text-[#1a365d]">DỰ ÁN TIN DÙNG</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Technical Excellence */}
      <section className="py-20 md:py-32 bg-white relative z-10">
        <div className="container mx-auto px-6 md:px-12">
          <div className="text-center mb-16 md:mb-24 space-y-4">
             <span className="text-[#89aad3] font-heading font-black tracking-[0.3em] uppercase text-[10px] md:text-xs">CÔNG NGHỆ ĐI ĐẦU</span>
             <h2 className="text-3xl md:text-5xl font-heading font-black text-[#1a365d] tracking-tighter">Đặc Tính Kỹ Thuật</h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 md:gap-8">
            {[
              { icon: Cpu, title: "Smart Chip Core", desc: "Điều khiển nhiệt độ chính xác tới 0.1 độ C, chống quá nhiệt lõi sưởi." },
              { icon: Waves, title: "Lưu Lượng Dày Mịn", desc: "Hệ thống vòi phun hợp kim cao cấp giúp khói tỏa đều và cực kỳ dày." },
              { icon: Settings, title: "DMX 512 Pro", desc: "Tương thích hoàn hảo với mọi bàn điều khiển ánh sáng sân khấu Pro." },
              { icon: ShieldCheck, title: "An Toàn Tuyệt Đối", desc: "Cảm biến tự ngắt thông minh khi cạn dung dịch hoặc có sự cố." }
            ].map((item, idx) => (
              <div key={idx} className="group p-8 md:p-10 rounded-[2rem] md:rounded-[3rem] bg-[#e8ebf2]/40 border-2 border-transparent hover:border-[#4981cf] hover:bg-white transition-all duration-500 shadow-sm hover:shadow-2xl">
                <div className="w-14 h-14 md:w-16 md:h-16 bg-[#4981cf] text-white rounded-[1.2rem] md:rounded-[1.5rem] flex items-center justify-center mb-6 md:mb-10 shadow-xl shadow-[#4981cf]/30 group-hover:rotate-12 transition-transform">
                  <item.icon className="w-6 h-6 md:w-8 md:h-8" />
                </div>
                <h4 className="text-xl md:text-2xl font-heading font-black text-[#1a365d] mb-4 md:mb-6">{item.title}</h4>
                <p className="text-[#1a365d] text-sm md:text-base font-bold opacity-70 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Product List */}
      <section 
        className="relative py-20 md:py-32 bg-[#4981cf] z-10 shadow-inner" 
        id="products"
      >
        <div className="container mx-auto px-6 md:px-12">
          <div className="text-center max-w-3xl mx-auto mb-16 md:mb-24">
            <h2 className="text-4xl md:text-6xl font-heading font-black text-white mb-6 md:mb-8 tracking-tighter drop-shadow-md">Sản Phẩm Tiêu Biểu</h2>
            <p className="text-[#cadaee] font-black tracking-[0.2em] text-[10px] md:text-xs uppercase italic opacity-90">Thiết bị tối tân - Hiệu ứng đỉnh cao</p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12">
            {[
              { name: "Máy Khói 1500W DMX", price: "2.450.000đ", img: machine1500w, badge: "Best Seller", desc: "Hệ thống điều khiển Pro, dành cho sân khấu chuyên nghiệp với lưu lượng cực lớn." },
              { name: "Máy Khói 400W Mini", price: "850.000đ", img: machine400w, badge: "New Arrival", desc: "Lên khói nhanh, nhỏ gọn, lý tưởng cho phòng karaoke gia đình và tiệc nhỏ." },
              { name: "Máy Khói Lạnh 3000W", price: "5.800.000đ", img: machine3000w, badge: "Premium", desc: "Hiệu ứng khói bay là là mặt đất, tạo không gian huyền ảo đẳng cấp cho Gala Wedding." },
              { name: "Dung Dịch Khói 5L", price: "250.000đ", img: liquid5l, badge: "Essential", desc: "Khói trắng, dày lâu tan, không mùi và đạt chuẩn an toàn sức khỏe tuyệt đối." },
              { name: "Máy Khói 900W Pro", price: "1.250.000đ", img: machine1500w, badge: "Hot", desc: "Công suất mạnh mẽ cho quán Bar, Club và các show diễn âm nhạc quy mô vừa." },
              { name: "Combo Stage Pro", price: "7.500.000đ", img: machine3000w, badge: "Save 15%", desc: "Bộ giải pháp toàn diện bao gồm máy khói lạnh, máy 1500W và 10L dung dịch." },
            ].map((item, idx) => (
              <motion.div 
                key={idx}
                whileHover={{ y: -10 }}
                className="group bg-white rounded-[2.5rem] md:rounded-[3.5rem] overflow-hidden shadow-2xl transition-all duration-500 flex flex-col h-full"
              >
                {/* Product Image Area */}
                <div className="relative h-60 md:h-72 overflow-hidden bg-[#e8ebf2]">
                  <div className="absolute top-4 left-4 md:top-6 md:left-6 z-20">
                     <span className="bg-[#4981cf] text-white px-4 md:px-5 py-1.5 md:py-2 rounded-full font-black text-[8px] md:text-[9px] uppercase tracking-widest shadow-lg">
                       {item.badge}
                     </span>
                  </div>
                  <motion.img 
                    whileHover={{ scale: 1.1 }}
                    transition={{ duration: 0.8 }}
                    src={item.img} 
                    className="w-full h-full object-cover transition-transform"
                    alt={item.name}
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>

                {/* Content Area */}
                <div className="p-8 md:p-10 flex flex-col flex-1">
                  <div className="flex justify-between items-start mb-3 md:mb-4">
                    <h3 className="text-xl md:text-2xl font-heading font-black text-[#1a365d] leading-tight pr-4">{item.name}</h3>
                  </div>
                  <div className="flex items-center gap-1.5 md:gap-2 mb-4 md:mb-6 text-[#4981cf]">
                     <Star className="w-3.5 h-3.5 md:w-4 md:h-4 fill-current" />
                     <Star className="w-3.5 h-3.5 md:w-4 md:h-4 fill-current" />
                     <Star className="w-3.5 h-3.5 md:w-4 md:h-4 fill-current" />
                     <Star className="w-3.5 h-3.5 md:w-4 md:h-4 fill-current" />
                     <Star className="w-3.5 h-3.5 md:w-4 md:h-4 fill-current" />
                     <span className="text-[9px] md:text-[10px] font-black text-[#1a365d]/40 ml-2">(128+)</span>
                  </div>
                  <p className="text-[#1a365d] text-sm md:text-base font-bold opacity-60 leading-relaxed mb-8 md:mb-10 flex-1">{item.desc}</p>
                  
                  <div className="flex items-center justify-between mt-auto pt-5 md:pt-6 border-t border-[#e8ebf2]">
                    <span className="text-2xl md:text-3xl font-black text-[#4981cf] tracking-tighter">{item.price}</span>
                    <button className="w-12 h-12 md:w-14 md:h-14 bg-[#1a365d] text-white rounded-xl md:rounded-2xl flex items-center justify-center hover:bg-[#4981cf] transition-all shadow-xl active:scale-90">
                      <ShoppingCart className="w-5 h-5 md:w-6 md:h-6" />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
          
          <div className="mt-16 md:mt-24 text-center">
             <button onClick={() => navigate('/catalog')} className="w-full sm:w-auto inline-flex items-center justify-center gap-4 bg-white/10 backdrop-blur-md border-2 border-white/30 text-white px-10 md:px-16 py-5 md:py-6 rounded-full font-black text-[10px] md:text-xs tracking-[0.2em] md:tracking-[0.3em] uppercase hover:bg-white hover:text-[#4981cf] transition-all">
               XEM TẤT CẢ SẢN PHẨM <ArrowRight className="w-4 h-4 md:w-5 md:h-5" />
             </button>
          </div>
        </div>
      </section>

      {/* Applications */}
      <section className="py-20 md:py-32 bg-[#e8ebf2] relative z-20">
        <div className="container mx-auto px-6 md:px-12">
          <div className="flex flex-col md:flex-row items-center md:items-end justify-between mb-16 md:mb-24 gap-8 text-center md:text-left">
            <div className="space-y-4">
              <span className="text-[#89aad3] font-heading font-black tracking-[0.3em] md:tracking-[0.4em] uppercase text-[10px] md:text-xs">KHÔNG GIAN BIẾN HÓA</span>
              <h2 className="text-4xl md:text-6xl font-heading font-black text-[#1a365d] tracking-tighter">Ứng Dụng Thực Tế</h2>
            </div>
            <p className="max-w-md text-[#1a365d] font-bold opacity-70 text-base md:text-lg leading-relaxed">DuongDIY đồng hành cùng mọi không gian, từ sân khấu lớn đến những buổi tiệc nhỏ ấm cúng.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 md:gap-8">
            {[
              { title: "Sân Khấu Pro", img: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=600&q=80" },
              { title: "Club & Bar", img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80" },
              { title: "Studio Chụp Ảnh", img: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80" },
              { title: "Đám Cưới Cao Cấp", img: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80" }
            ].map((item, idx) => (
              <div key={idx} className="relative group h-[400px] md:h-[500px] rounded-[2.5rem] md:rounded-[3.5rem] overflow-hidden shadow-2xl border-4 border-white">
                <img src={item.img} className="absolute inset-0 w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" alt={item.title} />
                <div className="absolute inset-0 bg-gradient-to-t from-[#1a365d] to-transparent opacity-60 group-hover:opacity-90 transition-opacity" />
                <div className="absolute bottom-10 md:bottom-12 left-10 md:left-12 right-10 md:right-12 z-10">
                  <h4 className="text-2xl md:text-3xl font-heading font-black text-white tracking-tighter mb-4">{item.title}</h4>
                  <div className="w-12 h-1.5 md:w-14 md:h-2 bg-[#cadaee] rounded-full transform origin-left transition-transform scale-x-0 group-hover:scale-x-100" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section 
        className="relative py-20 md:py-32 bg-[#89aad3] z-10 shadow-xl" 
        id="testimonials"
      >
        <div className="container mx-auto px-6 md:px-12 relative z-10">
          <div className="text-center max-w-3xl mx-auto mb-16 md:mb-24">
            <h2 className="text-4xl md:text-6xl font-heading font-black text-white mb-6 md:mb-8 tracking-tighter drop-shadow-md">Khách Hàng Nói Gì</h2>
            <p className="text-white font-black tracking-[0.2em] text-[10px] md:text-xs uppercase italic opacity-80">Uy tín tạo nên từ sự hài lòng thực tế</p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8 md:gap-10">
            {[
              { name: "Anh Tuấn (DJ)", role: "QUÁN BAR QUẬN 1", text: "Máy khói DuongDIY đánh rất bốc, lượng khói phủ kín sàn chỉ trong vài giây. Rất hài lòng về hiệu suất của máy 1500W!" },
              { name: "Chị Lan Anh", role: "QUẢN LÝ SỰ KIỆN", text: "Mình mua 3 máy cho công ty tổ chức sự kiện. Máy chạy êm, ít bị nghẹt sưởi như mấy dòng giá rẻ trước đây. Sẽ ủng hộ dài lâu." },
              { name: "Minh Hoàng", role: "KARAOKE VIP", text: "Dung dịch khói bạc hà mùi cực kỳ dễ chịu, khách khen rất nhiều. Máy khói mini 400W nhỏ mà có võ, lên khói rất đều." }
            ].map((item, idx) => (
              <motion.div 
                key={idx}
                whileHover={{ y: -10, scale: 1.02 }}
                className="bg-white p-8 md:p-12 rounded-[2.5rem] md:rounded-[3.5rem] shadow-2xl relative overflow-hidden"
              >
                <div className="absolute top-0 right-0 w-20 md:w-24 h-20 md:h-24 bg-[#4981cf]/10 rounded-bl-[3rem] md:rounded-bl-[4rem]" />
                <div className="flex text-[#4981cf] mb-8 md:mb-10">
                  {[...Array(5)].map((_, i) => <Award key={i} className="w-5 h-5 md:w-6 md:h-6 fill-current" />)}
                </div>
                <p className="text-[#1a365d] text-lg md:text-xl font-bold leading-relaxed mb-8 md:mb-10 italic">"{item.text}"</p>
                <div className="pt-6 md:pt-8 border-t border-[#cadaee]">
                  <h4 className="text-xl md:text-2xl font-black text-[#1a365d]">{item.name}</h4>
                  <p className="text-[#4981cf] text-[9px] md:text-xs font-black uppercase tracking-[0.2em] mt-2">{item.role}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 md:py-32 bg-white relative z-5">
        <div className="container mx-auto px-6 md:px-12">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-16 md:mb-24">
              <span className="text-[#89aad3] font-heading font-black tracking-[0.3em] md:tracking-[0.4em] uppercase text-[10px] md:text-xs">GIẢI ĐÁP THẮC MẮC</span>
              <h2 className="text-4xl md:text-6xl font-heading font-black text-[#1a365d] tracking-tighter mt-4 md:mt-6">Câu Hỏi Thường Gặp</h2>
            </div>
            <div className="space-y-6 md:space-y-8">
              { [
                { q: "Làm thế nào để vệ sinh lõi sưởi máy khói?", a: "Sử dụng hỗn hợp nước cất và giấm trắng (tỷ lệ 8:2) chạy máy trong 5-10 phút sau mỗi 40 giờ sử dụng để loại bỏ cặn dung dịch." },
                { q: "Có cần sử dụng dung dịch chuyên dụng không?", a: "Rất nên. Dung dịch của DuongDIY được tối ưu hóa cho lõi sưởi của máy, giúp kéo dài tuổi thọ thiết bị và tạo khói dày, an toàn hơn." },
                { q: "Chính sách bảo hành như thế nào?", a: "Chúng tôi bảo hành 12 tháng cho lỗi kỹ thuật của nhà sản xuất và hỗ trợ bảo trì trọn đời cho mọi khách hàng." }
              ].map((item, idx) => (
                <div key={idx} className="p-8 md:p-10 rounded-[2rem] md:rounded-[3rem] bg-[#e8ebf2]/40 border-2 border-transparent hover:border-[#4981cf] transition-all group shadow-sm hover:shadow-xl">
                  <h4 className="text-xl md:text-2xl font-heading font-black text-[#1a365d] mb-4 md:mb-6 flex items-start gap-4 md:gap-6">
                    <div className="shrink-0 w-10 h-10 md:w-12 md:h-12 rounded-xl md:rounded-2xl bg-white flex items-center justify-center text-[#4981cf] shadow-md group-hover:bg-[#4981cf] group-hover:text-white transition-colors">
                      <CheckCircle2 className="w-5 h-5 md:w-6 md:h-6" />
                    </div> 
                    <span className="pt-1 md:pt-2">{item.q}</span>
                  </h4>
                  <p className="text-[#1a365d] text-base md:text-lg font-bold opacity-70 pl-14 md:pl-[4.5rem] leading-relaxed">{item.a}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Newsletter */}
      <section className="py-20 md:py-32 px-6 md:px-12 bg-[#e8ebf2] relative z-10">
        <div className="container mx-auto">
          <div className="bg-[#1a365d] rounded-[3rem] md:rounded-[5rem] p-10 md:p-20 relative overflow-hidden flex flex-col lg:flex-row items-center justify-between gap-12 md:gap-16 shadow-[0_50px_100px_rgba(26,54,93,0.3)]">
             <div className="absolute top-0 right-0 w-2/3 h-full bg-[#4981cf]/20 blur-[100px] md:blur-[150px] rounded-full" />
             <div className="space-y-6 md:space-y-8 relative z-10 max-w-2xl text-center lg:text-left">
                <h2 className="text-4xl md:text-7xl font-heading font-black text-white tracking-tighter leading-tight md:leading-none">Nhận Ưu Đãi <br className="hidden md:block"/><span className="text-[#cadaee]">Độc Quyền 15%</span></h2>
                <p className="text-white/80 text-lg md:text-xl font-bold italic">Đăng ký để nhận báo giá sỉ và cập nhật công nghệ mới nhất từ DuongDIY.</p>
             </div>
             <div className="relative z-10 w-full max-w-lg">
                <div className="flex flex-col sm:flex-row bg-white p-2 md:p-4 rounded-3xl md:rounded-[2.5rem] shadow-2xl gap-2">
                   <input type="email" placeholder="Email nhận ưu đãi..." className="flex-1 bg-transparent px-6 md:px-8 py-4 text-[#1a365d] placeholder-[#1a365d]/30 outline-none font-black text-base md:text-lg" />
                   <button className="bg-[#4981cf] text-white px-8 md:px-12 py-4 rounded-2xl md:rounded-[1.8rem] font-black text-[10px] md:text-xs uppercase tracking-[0.2em] hover:bg-[#1a365d] transition-all shadow-xl">GỬI NGAY</button>
                </div>
             </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer 
        className="bg-[#1a365d] pt-20 md:pt-32 pb-16 md:pb-20 relative overflow-hidden z-0"
      >
        <div className="container mx-auto px-6 md:px-12 relative z-10 grid sm:grid-cols-2 lg:grid-cols-4 gap-16 md:gap-24 text-white">
          <div className="sm:col-span-2 space-y-10 md:space-y-12">
            <div className="flex items-center gap-4 justify-center sm:justify-start">
              <div className="w-12 h-12 md:w-14 md:h-14 bg-white rounded-xl md:rounded-2xl flex items-center justify-center font-black italic text-[#1a365d] text-xl md:text-2xl shadow-xl">D</div>
              <span className="text-3xl md:text-4xl font-black italic tracking-tighter font-heading">DUONGDIY</span>
            </div>
            <p className="text-white/60 font-bold text-lg md:text-xl leading-relaxed max-w-md mx-auto sm:mx-0 text-center sm:text-left">
              Chuyên gia cung cấp giải pháp máy tạo khói sân khấu hàng đầu Việt Nam. 
              Mang nghệ thuật khói và ánh sáng tới mọi không gian của bạn.
            </p>
            <div className="flex gap-4 md:gap-6 pt-2 justify-center sm:justify-start">
               {[Facebook, Twitter, Instagram, Globe].map((Icon, i) => (
                 <div key={i} className="w-12 h-12 md:w-14 md:h-14 bg-white/5 rounded-xl md:rounded-[1.5rem] flex items-center justify-center hover:bg-white hover:text-[#1a365d] transition-all cursor-pointer border-2 border-white/10 shadow-lg">
                   <Icon className="w-5 h-5 md:w-6 md:h-6" />
                 </div>
               ))}
            </div>
          </div>

          <div className="space-y-8 md:space-y-12 text-center sm:text-left">
             <h4 className="text-lg md:text-xl font-heading font-black tracking-[0.2em] md:tracking-[0.3em] uppercase text-[#cadaee]">LIÊN HỆ</h4>
             <ul className="space-y-6 md:space-y-8 text-white/70 font-bold text-base md:text-lg">
               <li className="flex items-center justify-center sm:justify-start gap-4 md:gap-6 hover:text-white transition-colors cursor-pointer"><MessageSquare className="w-5 h-5 md:w-6 md:h-6 text-[#cadaee]" /> duongdiy@gmail.com</li>
               <li className="flex items-center justify-center sm:justify-start gap-4 md:gap-6 hover:text-white transition-colors cursor-pointer"><Users className="w-5 h-5 md:w-6 md:h-6 text-[#cadaee]" /> 09xx xxx xxx</li>
               <li className="flex items-center justify-center sm:justify-start gap-4 md:gap-6"><Globe className="w-5 h-5 md:w-6 md:h-6 text-[#cadaee]" /> TP. Hồ Chí Minh, VN</li>
             </ul>
          </div>

          <div className="space-y-8 md:space-y-12 text-center sm:text-left">
             <h4 className="text-lg md:text-xl font-heading font-black tracking-[0.2em] md:tracking-[0.3em] uppercase text-[#cadaee]">HỖ TRỢ</h4>
             <ul className="space-y-6 md:space-y-8 text-white/70 font-bold text-base md:text-lg">
               <li className="hover:text-white transition-colors cursor-pointer">Hướng Dẫn Vệ Sinh</li>
               <li className="hover:text-white transition-colors cursor-pointer">Chính Sách Bảo Hành</li>
               <li className="hover:text-white transition-colors cursor-pointer">Chính Sách Đổi Trả</li>
               <li className="hover:text-white transition-colors cursor-pointer">Câu Hỏi Thường Gặp</li>
             </ul>
          </div>
        </div>
        <div className="container mx-auto px-6 md:px-12 mt-24 md:mt-40 pt-10 md:pt-12 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-6 md:gap-8 text-[9px] md:text-[11px] font-black uppercase tracking-[0.3em] md:tracking-[0.4em] text-white/20 text-center">
          <p>© 2026 DUONGDIY. PROFESSIONAL STAGE EQUIPMENT.</p>
          <div className="flex gap-8 md:gap-12">
            <a href="#" className="hover:text-white transition-colors">PRIVACY</a>
            <a href="#" className="hover:text-white transition-colors">TERMS</a>
            <a href="#" className="hover:text-white transition-colors">COOKIES</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
